version: "3.9"
services:
  db:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/user_pass
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./db/data:/data
      - ./db/logs:/logs
      - ./db/import:/var/lib/neo4j/import
      - ./db/plugins:/plugins
  web:
    build: docker/web/
    command: /bin/bash -c "./scripts/entrypoint.sh"
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db